version: '3'

services:
  database:
    container_name: training_cicd_database
    build:
      context: ./docker/database
    environment:
      - MYSQL_DATABASE=rest_api
      - MYSQL_ROOT_PASSWORD=greatpwdroot
    command: mysqld --sql-mode=""
    ports:
      - "3306:3306"
    volumes:
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/database/data:/var/lib/mysql

  php-fpm:
    container_name: training_cicd_phpfpm
    build:
      context: ./docker/php-fpm
    depends_on:
      - database
    environment:
      - APP_ENV=dev
      - APP_SECRET=e614c43bd6af3da28277f9817c6363e8
      - DATABASE_URL=mysql://root:greatpwdroot@database:3306/rest_api?serverVersion=5.7&charset=utf8mb4
    volumes:
      - ./:/var/www
    links:
      - database

  nginx:
    container_name: training_cicd_nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
