FROM php:7.4-fpm

USER root

WORKDIR /var/www

# Install dependencies
RUN apt-get update

RUN pecl install xdebug && docker-php-ext-enable xdebug


# Copy source code
COPY . /var/www

# setup composer and symfony
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN composer install --prefer-dist --no-interaction --working-dir="/var/www"
