name: Pull-Request title check
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  lint-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: deepakputhraya/action-pr-title@master
      with:
        regex: '.*(Deps|feature-\d{1,6}).*' # Regex the title should match.
        min_length: 7 # Min length of the title
        max_length: 200 # Max length of the title
        github_token: ${{ github.token }} # Default: ${{ github.token }}
